config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    The
    %a{href: 'https://www.railstutorial.org/'}
      Ruby on Rails Tutorial
    by
    %a{href: 'https://www.michaelhartl.com/'}
      Michel Hertl
  %nav
    %ul
      %li= link_to('About', about_path)
      %li= link_to('Contact', contact_path)
      %li
        %a{href: 'https://news.railstutorial.org'}
          News

app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-fixed-top.navbar-inverse
    .container
      = link_to "sample app", root_path, id: "logo"
      %nav
        .navbar-header
          %button.navbar-toggle.collapsed{ :type => "button", "data-toggle" => "collapse", "data-target" => "#bs-example-navbar-collapse-1", "aria-expanded" => "false" }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        %ul.nav.navbar-nav.navbar-right.collapse.navbar-collapse#bs-example-navbar-collapse-1
          %li= link_to "Home", root_path
          %li= link_to "Help", help_path
          - if logged_in?
            %li= link_to "Users", users_path
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li
                  = link_to "Log out", logout_path, method: :delete
          - else
            %li= link_to "Log in", login_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= full_title(yield(:title))
    %meta{:charset => "utf-8"}/
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', |
      'data-turbolinks-track': 'reload'                |
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?